### ISSUE TITLE
Why would you name the main folder RemoteTech ?

### ISSUE THREAD

**Issue by Mecripp** [RemoteTechnologiesGroup/RemoteTech-Antennas#1]
ran into this post from ( banditsan) (@Snark Hi, 
Found interesting conflict with RemoteTech-Antennas a standalone without RemoteTech. jx2_RemoteTech.cfg finds RemoteTech folder and executes -MODULE[ModuleDeployableAntenna] {}. After this all your 3 antennas do not work. Tryed to to play with config myself but im still kinda noob on ModuleManager  
Will post if will find any fixes myself )

https://forum.kerbalspaceprogram.com/index.php?/topic/153125-145-jx2antenna-v205-giant-1000g-antenna-for-big-solar-systems/&page=8

The RemoteTech patch Snark has for remotetech is wrong I'm pretty sure and I have post what I think it should be the MM is still going to run like it has RemoteTech mod installed so why wouldn't you just have the main folder be RemoteTech-Antennas     ?  not RemoteTech/RemoteTech-Antennas would think then other MM for RemoteTech wouldn't run that way ?

**Comment by snark** [comment]
Pretty sure you tagged in the wrong GH user!

**Comment by Mecripp** [comment]
Well this is the mod RemoteTech-Antennas ? and if your the same snark has here https://forum.kerbalspaceprogram.com/index.php?/topic/153125-145-jx2antenna-v205-giant-1000g-antenna-for-big-solar-systems/
then I got it right has its RemoteTech-Antennas folder setup that's the problem and Snark jx2antenna antennas remotetech cfg are wrong also this is what it should look like  `// Compatibility with the RemoteTech mod.

@PART[jx2LDA]:AFTER[RemoteTech] {
	// RemoteTech antennas use ModuleAnimateGeneric, so need
	// to use that instead of ModuleDeployableAntenna.

	!MODULE[ModuleDataTransmitter] {}
	@MODULE[ModuleAnimateGeneric]
	{
		%allowManualControl = false
	}
	MODULE
	{
		name = ModuleAnimateGeneric
		animationName = deployHexes
		allowManualControl = false
		isOneShot = false

		startEventGUIName = Extend
		endEventGUIName = Retract
		actionGUIName = Toggle Antenna
	}

	// This is what makes it work with RemoteTech.
	%MODULE[ModuleRTAntenna] {
		%Mode0DishRange = 0
		%Mode1DishRange = 1000000000000
		%EnergyCost = 5
		%MaxQ = 6000
		%DishAngle = 0.002

		%DeployFxModules = 0

		%TRANSMITTER {
			%PacketInterval = 0.3
			%PacketSize = 2
			%PacketResourceCost = 15.0
		}
	}

	%MODULE[ModuleSPUPassive] {}
}


@PART[jw1MDA|ju1MDA]:AFTER[RemoteTech] {
	// RemoteTech antennas use ModuleAnimateGeneric, so need
	// to use that instead of ModuleDeployableAntenna.

	!MODULE[ModuleDataTransmitter] {}
	@MODULE[ModuleAnimateGeneric]
	{
		%allowManualControl = false
	}
	MODULE
	{
		name = ModuleAnimateGeneric
		animationName = deployHexes
		allowManualControl = false
		isOneShot = false

		startEventGUIName = Extend
		endEventGUIName = Retract
		actionGUIName = Toggle Antenna
	}

	// This is what makes it work with RemoteTech.
	%MODULE[ModuleRTAntenna] {
		%Mode0DishRange = 0
		%Mode1DishRange = 300000000000
		%EnergyCost = 3
		%MaxQ = 6000
		%DishAngle = 0.006

		%DeployFxModules = 0

		%TRANSMITTER {
			%PacketInterval = 0.3
			%PacketSize = 2
			%PacketResourceCost = 18.0
		}
	}

	%MODULE[ModuleSPUPassive] {}
}


// AntennaSleep adds a ModuleDeployableSleep to every part that has
// a ModuleDeployableAntenna on it. Since we've just removed the
// ModuleDeployableAntenna, the ModuleDeployableSleep won't work right,
// so we need to remove that if it's there.
@PART[jx2LDA|jw1MDA|ju1MDA]:AFTER[AntennaSleep]:NEEDS[RemoteTech] {
	-MODULE[ModuleDeployableSleep] {}
}
}
  `

**Comment by Mecripp** [comment]
Whoops and my bad I see I miss read the cfg but it is still not right has it not taking out all the stock stuff but miss read -MODULE[ModuleDeployableAntenna] {}
thought when I seen it, It was -MODULE[ModuleAnimateGeneric] {}

**Comment by Gordon-Dry** [comment]
Or in short words:
When you release a mod / part pack then give it a unique folder.
Don't put it into the folder of another mod.

**Comment by Gordon-Dry** [comment]
And btw this is nearly the same release as the StockRemoteTechAntennas which are part of the CommnetConstellation mod:
https://github.com/KSP-TaxiService/CommNetConstellation/tree/develop/GameData

The only differences are that

1. the part.cfg of this pack are Windows (CR LF) UTF-8 and those embedded into CommnetConstellation are Unix (LF) UTF-8
2. the CommnetConstellation thing got an extra config called Game\StockRemoteTechAntennas\StockRemoteTech_Antennas.cfg

**Comment by KSP-TaxiService** [comment]
Whoops, I didn't notice this issue. I renamed to RemoteTechRedev name. ([Commit](https://github.com/RemoteTechnologiesGroup/RemoteTech-Complete/commit/a0e6598cf398cb7c744f2e1eabdfef546c18cab3)).

Due to the copyright issue, I am going to remove CNC's whole StockRemoteTechAntennas folder and amend CNC's CKAN metadata to download the mod off Spacedock.

Thanks!
